# Spring Boot 配置文件 - 生产环境
server:
  port: 8080
  # 生产环境优化配置
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    max-connections: 10000

spring:
  # 数据源配置 - 生产环境
  datasource:
    url: jdbc:mysql://your-production-host:3306/framework_db?serverTimezone=Asia/Shanghai&useSSL=true&characterEncoding=utf8mb4&rewriteBatchedStatements=true&cachePrepStmts=true&useServerPrepStmts=true
    username: ${DB_USERNAME:root}  # 建议使用环境变量
    password: ${DB_PASSWORD:your_password}  # 建议使用环境变量
    # 连接池配置（HikariCP）
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  
  # Redis 配置 - 生产环境
  data:
    redis:
      host: ${REDIS_HOST:your-redis-host}     # 使用环境变量
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}            # 使用环境变量
      database: 0
      timeout: 5000ms                         # 生产环境增加超时时间
      lettuce:
        pool:
          max-active: 20                      # 生产环境增加连接数
          max-wait: -1ms
          max-idle: 10
          min-idle: 5                         # 保持最小空闲连接
        shutdown-timeout: 100ms

# MyBatis Plus 配置 - 生产环境
mybatis-plus:
  configuration:
    # 生产环境关闭 SQL 日志（覆盖公共配置）
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 开启二级缓存
    cache-enabled: true

# 日志配置 - 生产环境
logging:
  level:
    root: WARN
    com.zhu: INFO
    com.zhu.mapper: WARN
  file:
    name: logs/application.log
    max-size: 100MB
    max-history: 30
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'

# SpringDoc OpenAPI 配置 - 生产环境
springdoc:
  api-docs:
    enabled: false  # 生产环境建议关闭 API 文档
  swagger-ui:
    enabled: false  # 生产环境建议关闭 Swagger UI

# 安全配置
management:
  endpoints:
    web:
      exposure:
        include: health,info  # 只暴露健康检查和信息端点
  endpoint:
    health:
      show-details: when-authorized
